// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANojHl-JzTxGGmM3wHGTzHSjllBOTQOxk',
    appId: '1:116797597909:web:372e234e1a8c1d28e9da5c',
    messagingSenderId: '116797597909',
    projectId: 'hanouty-6a822',
    authDomain: 'hanouty-6a822.firebaseapp.com',
    storageBucket: 'hanouty-6a822.appspot.com',
    measurementId: 'G-7DLL9CW9MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF88YUf0ORiJZb1UyzXhM4AQPHfWqL0lk',
    appId: '1:116797597909:android:c78503cd7d0b4a3de9da5c',
    messagingSenderId: '116797597909',
    projectId: 'hanouty-6a822',
    storageBucket: 'hanouty-6a822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1l4_OVBfRhlFzf4PPRL6b-CNY-AOF3Y',
    appId: '1:116797597909:ios:8c6ce67c760ad3b0e9da5c',
    messagingSenderId: '116797597909',
    projectId: 'hanouty-6a822',
    storageBucket: 'hanouty-6a822.appspot.com',
    iosClientId: '116797597909-pcj475ioho2kj068c91rtks0hnkcou86.apps.googleusercontent.com',
    iosBundleId: 'com.devbourheeem.hanouty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1l4_OVBfRhlFzf4PPRL6b-CNY-AOF3Y',
    appId: '1:116797597909:ios:8c6ce67c760ad3b0e9da5c',
    messagingSenderId: '116797597909',
    projectId: 'hanouty-6a822',
    storageBucket: 'hanouty-6a822.appspot.com',
    iosClientId: '116797597909-pcj475ioho2kj068c91rtks0hnkcou86.apps.googleusercontent.com',
    iosBundleId: 'com.devbourheeem.hanouty',
  );
}
